1911

diff --git a/wercker.yml b/wercker.yml
--- a/wercker.yml
+++ b/wercker.yml
@@ -33,3 +33,34 @@ build:
           docker run --rm -d -p 5000:5000 --name testcontainer --network=$DOCKER_NETWORK_NAME docker.io/$USERNAME/direct-docker-golang:latest
           echo running docker ps
           docker ps
+    - script:
+        name: Wait for container to start
+        code: |
+          until $(curl --output /dev/null --silent --head --fail http://testcontainer:5000); do printf '.'; sleep 5; done
+    - script:
+        name: Test the container that we started using docker-run
+        code: |
+          if curlOutput=`curl -s testcontainer:5000`; then
+            export expected="Hello World!!"
+            if [ "$curlOutput" == "$expected" ]; then
+              echo "Test passed: container gave expected response: " $expected
+            else
+              echo "Test failed: container gave unexpected response: " $curlOutput
+              echo "The expected response was: " $expected
+              exit 1
+            fi
+          else
+            echo "Test failed: container did not respond"
+            exit 1
+          fi
+    - script:
+        name: kill the container using docker kill
+        code: |
+          docker kill testcontainer
+          echo running docker ps
+          docker ps
+    - script:
+        name: push the newly-created image to a repository
+        code: |
+          docker login -u $USERNAME -p $PASSWORD
+          docker push docker.io/$USERNAME/direct-docker-golang:latest
